[project]
name = "invoiceflow"
version = "0.1.0"
description = ""
authors = [
    {name = "Lukas Hamm",email = "lukashammdev@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic (>=2.12.5,<3.0.0)",
    "pydantic-settings (>=2.13.1,<3.0.0)",
    "openai (>=2.30.0,<3.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "pypdf2 (>=3.0.1,<4.0.0)",
    "pymupdf (>=1.27.2.2,<2.0.0.0)"
]

[tool.poetry]
packages = [{include = "invoiceflow", from = "src"}]

[tool.poetry.scripts]
invoiceflow = "invoiceflow.app:run"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
